### ISSUE TITLE
Test fails on windows

### ISSUE THREAD

**Issue by JaapD** [AdamBien/nano#1]
On windows the ContextsTest fails, I suggest the following change:
        Path path = Paths.get("./src/test/js/hello/duke.js");
        String actual = Contexts.extractContext(path);
        actual = actual.replace('\', '/');
        assertThat(actual, is("/src/test/js/hello/duke"));

**Comment by AdamBien** [comment]
Thanks for your test. I'm comparing Path objects now -> it should be OS-independent. Does it work?

**Comment by JaapD** [comment]
Yes, it works.
Thanks for learning Path :-)
